### ISSUE TITLE
Submodule maybe?

### ISSUE THREAD

**Issue by stkim1** [RichardLitt/meta-knowledge#1]
It would be handy if you could submodule the referred repositories so one can pull them altogether in one go. 

`subtree` is rather copyright invasive that I'd not look into it though.

**Comment by RichardLitt** [comment]
As it is, it should be relatively easy to pull them all; just copy and paste them into a list and use xargs with `git clone`. I'm not sure that doing more than listing them is something I want to do, though. 

Wouldn't submoduling them mean I would need to keep updating this repo? I don't want to do that more than I have to.

**Comment by ewnd9** [comment]
I use the following script for updating repos in the same directory where the script is stored. Hope it will help, but you need to clone them manually first

```sh
#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for i in $(ls); do
  if [ -d "$DIR/$i/.git" ]
  then
    cd "$DIR/$i"
    BRANCH="$(git symbolic-ref --short -q HEAD)"
    git pull origin $BRANCH
    cd ..
  fi
done
```

**Comment by stkim1** [comment]
@ewnd9 Thanks a ton! That's nice of you!

@RichardLitt First of all, I appreciate your time to put together this mega-awesome list. I'd imagine you'd  have spent a good chunk of your time to colllect, read, & edit the materials to present. No complains, only appreciation. My issue is not really an _issue_ per se. It's close to a suggestion, so to speak.

As far as I reckon, meta lists such as `awesome-` series are there to provide convenience of time and cognitive overhead reduction to potential readers. If you could, at least, add @ewnd9's script to somewhere in [README.md](https://github.com/RichardLitt/meta-knowledge/blob/master/README.md), that might be a smooth step forward. 

Anyway, Thanks for the list 👍

**Comment by RichardLitt** [comment]
> I'd imagine you'd have spent a good chunk of your time to colllect, read, & edit the materials to present.

Not too much - I just saw that people weren't consistent in looking for others, so I tried to make one that makes it easier. 

> My issue is not really an issue per se. It's close to a suggestion, so to speak.

Issues on GitHub can be enhancements. :) 

I'll link to the script. thanks for the suggestion.
