### ISSUE TITLE
Add more metadata on the repositories

### ISSUE THREAD

**Issue by lyz-code** [RichardLitt/meta-knowledge#46]
Hi, it would be nice to be able to have more metadata of the repositories, such as number of stars, last commit, watchers, contributors...

Something like [this](https://github.com/toniblyx/my-arsenal-of-aws-security-tools) site. So if you agree I don't mind doing a PR with the updated readme entries with the following format:

```markdown
| Name | Topics | Popularity | Metadata |
| ---------- | :---------- | :----------: | :----------: |
| [**Blue Book**](https://github.com/lyz-code/blue-book) | DevOps, Life automation, Python, Data analysis |[![stars](https://badgen.net/github/stars/lyz-code/blue-book)](https://badgen.net/github/stars/lyz-code/blue-book)| [![contributors](https://badgen.net/github/contributors/lyz-code/blue-book)](https://badgen.net/github/contributors/lyz-code/blue-book) [![watchers](https://badgen.net/github/watchers/lyz-code/blue-book)](https://badgen.net/github/watchers/lyz-code/blue-book) [![last-commit](https://badgen.net/github/last-commit/lyz-code/blue-book)](https://badgen.net/github/last-commit/lyz-code/blue-book) [![open-issues](https://badgen.net/github/open-issues/lyz-code/blue-book)](https://badgen.net/github/open-issues/lyz-code/blue-book) [![closed-issues](https://badgen.net/github/closed-issues/lyz-code/blue-book)](https://badgen.net/github/closed-issues/lyz-code/blue-book) |
```

Example:

| Name | Topics | Popularity | Metadata |
| ---------- | :---------- | :----------: | :----------: |
| [**Blue Book**](https://github.com/lyz-code/blue-book) | DevOps, Life automation, Python, Data analysis |[![stars](https://badgen.net/github/stars/lyz-code/blue-book)](https://badgen.net/github/stars/lyz-code/blue-book)| [![contributors](https://badgen.net/github/contributors/lyz-code/blue-book)](https://badgen.net/github/contributors/lyz-code/blue-book) [![watchers](https://badgen.net/github/watchers/lyz-code/blue-book)](https://badgen.net/github/watchers/lyz-code/blue-book) [![last-commit](https://badgen.net/github/last-commit/lyz-code/blue-book)](https://badgen.net/github/last-commit/lyz-code/blue-book) [![open-issues](https://badgen.net/github/open-issues/lyz-code/blue-book)](https://badgen.net/github/open-issues/lyz-code/blue-book) [![closed-issues](https://badgen.net/github/closed-issues/lyz-code/blue-book)](https://badgen.net/github/closed-issues/lyz-code/blue-book) |

**Comment by RichardLitt** [comment]
I'm not sure any of those metrics are metrics I care about. Size of repo might be one; but stars isn't, and neither is contributors, watchers, last commit, or issue stats. 

It's a good idea, though. I just don't think these things are necessary. Thank you.
