### ISSUE TITLE
Add 'Rules' Section

### ISSUE THREAD

**Issue by sergiomoraes** [RichardLitt/meta-knowledge#49]
There's a lot of good content compiled here and it's great to see so many people documenting (and sharing their documentation) on Github.

I do believe that a small section talking about basic rules or recommendations prior to adding a new repo to the list could be useful though.

After navigating a dozen or so repositories off the list, I've come across a couple that contain PDF versions of books that are not open-source or in the public domain. That, in my opinion, is a good example of something that could be added to the rules as something that should be avoided.

Other topics that could be covered are:

* Licenses: make sure the repositories have chosen and displayed the appropriate licenses so people know how to use the content they find

* Contributions: Proper contribution guidelines

* Link Back: Suggest a link back to this repository to stimulate the creation of a network of documentation and knowledge sharing

**Comment by RichardLitt** [comment]
>  I've come across a couple that contain PDF versions of books that are not open-source or in the public domain.

Are those the only things in those lists? Why should we avoid that? 

Regarding licenses: If there is a license in the top level, that should be fine. I'm not too worried about that. I also am not sure about contribution guidelines. This is mainly for notebooks that people have, and I don't mind if they don't accept contributions. 

Happy to suggest a link back. Want to PR this particular change?

**Comment by sergiomoraes** [comment]
> Are those the only things in those lists? Why should we avoid that?

My thought process was, trying to discourage the sharing of pirated content and adhering to Github's Terms of Service.

*Licenses and Contribution Guidelines*
I suggested these as part of a "rules" section to encourage people to think/talk about sharing their knowledge further. Even if they don't want contributions to their repositories, I believe there's benefit in suggesting that people share their thoughts around how they want their repositories to be used.

I think that "licenses" was most likely an unnecessary addition to the list, and calling the section "rules" might have been misguided.
Calling it "tips" or "suggestions" might better reflect what I was trying to say.

I can PR the 'link back' change for sure! What are your thoughts regarding what I said above? I hope I did a better job explaining my point, which, by the way, is just a suggestion, of course.

**Comment by RichardLitt** [comment]
I see where you're coming from for all of this, and I appreciate it. I ultimately started this just as a list of lists - not as in an arbiter. It's hard for me to imagine shifting to that. "Tips" is better, but it's still vaguely preachy. I just wanted to link to knowledge repos. I don't have the energy to do more than that.

> My thought process was, trying to discourage the sharing of pirated content and adhering to Github's Terms of Service.

If GitHub has an issue with a repo, they can take it down. I don't think linking to those repos is an issue. I'm not interested in being the police around what repositories are valid or not. It sounds like effort. 

As for contributing, isn't putting these notebooks publicly on GitHub already a statement of intent for it to be shared? 

I think a single line: "If you want to link back to this repo, do so!" would work well for me, in a PR. I don't know if I want anything more than that.
